[versions]
agp = "8.10.0"
core = "1.7.0"
kotlin = "2.0.21"
coreKtx = "1.17.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.9.4"
activityCompose = "1.11.0"
composeBom = "2024.10.00"
coroutines = "1.8.1"
navigation = "2.7.7"
roomExternalAntlr = "2.8.3"
roomCommonJvm = "2.8.4"
roomRuntimeAndroid = "2.8.4"
room = "2.6.1"

[libraries]
androidx-core = { module = "androidx.test:core", version.ref = "core" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-runner = { module = "androidx.test:runner", version.ref = "core" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }

androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }

# Compose
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
androidx-ui = { module = "androidx.compose.ui:ui" }
androidx-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }

#icons
androidx-icons-extended = { module = "androidx.compose.material:material-icons-extended" }


#room
room-runtime = {module = "androidx.room:room-runtime", version.ref = "room"}
room-ktx = {module = "androidx.room:room-ktx", version.ref = "room"}
room-compiler = {module = "androidx.room:room-compiler", version.ref = "room"}


androidx-material3 = { module = "androidx.compose.material3:material3" }

navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }

# Coroutines
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }


androidx-room-external-antlr = { group = "androidx.room", name = "room-external-antlr", version.ref = "roomExternalAntlr" }
androidx-room-common-jvm = { group = "androidx.room", name = "room-common-jvm", version.ref = "roomCommonJvm" }
androidx-room-runtime-android = { group = "androidx.room", name = "room-runtime-android", version.ref = "roomRuntimeAndroid" }

[bundles]
compose = [
    "androidx-ui",
    "androidx-ui-graphics",
    "androidx-ui-tooling",
    "androidx-material3",
    "androidx-activity-compose"
]

coroutines = [
    "coroutines-core",
    "coroutines-android"
]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
google-services = { id = "com.google.gms.google-services", version = "4.4.2" }
ksp = { id = "com.google.devtools.ksp", version = "2.0.21-1.0.25" }